/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.rpa.service;import org.junit.jupiter.api.Test;import static org.assertj.core.api.Assertions.assertThat;/**
                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                            */
class BotProductionReleaseServiceTest{private final BotProductionReleaseService service=new BotProductionReleaseService();/**
                                                                                                                                                                                                                                                      * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                      */
@Test void deploysGovernedBot(){var r=service.assess(new BotProductionReleaseService.Request("B1",true,true,95,true,true,true,true,true,1));assertThat(r.decision()).isEqualTo(BotProductionReleaseService.Decision.DEPLOY);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   */
@Test void blocksSecurityAndTestFailures(){var r=service.assess(new BotProductionReleaseService.Request("B2",false,false,50,false,false,false,true,true,1));assertThat(r.blockers()).hasSize(6);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    */
@Test void pilotsOperationalRisk(){var r=service.assess(new BotProductionReleaseService.Request("B3",true,true,95,true,true,true,false,false,10));assertThat(r.actions()).hasSize(3);}}
