/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.rpa.controller;import cn.zhuatech.rpa.common.ApiResponse;import cn.zhuatech.rpa.service.BotProductionReleaseService;import jakarta.validation.Valid;import org.springframework.web.bind.annotation.*;/**
                                                                                                                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                          */
@RestController @RequestMapping("/api/enterprise/rpa")public class BotProductionReleaseController{private final BotProductionReleaseService service;/**
                                                                                                                                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                              */
public BotProductionReleaseController(BotProductionReleaseService service){this.service=service;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               */
@PostMapping("/bot-production-release")public ApiResponse<BotProductionReleaseService.Assessment>assess(@Valid @RequestBody BotProductionReleaseService.Request request){return ApiResponse.ok(service.assess(request));}}
